<!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>  -->


<link rel="stylesheet" href="jqwidgets/styles/jqx.base.css" type="text/css" />
<!--<link rel="stylesheet" href="jqwidgets/styles/jqx.grp.css" type="text/css" />-->
<script src="css/v3/librerias/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="css/v3/librerias/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<link rel="stylesheet" type="text/css" href="css/v3/librerias/bootstrap-multiselect/bootstrap-multiselect.css">
<script type="text/javascript" src="jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="jqwidgets/jqxdata.js"></script>
<script type="text/javascript" src="jqwidgets/jqxinput.js"></script>
<script type="text/javascript" src="jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="jqwidgets/jqxdropdownlist.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.filter.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.sort.js"></script>
<script type="text/javascript" src="jqwidgets/jqxmenu.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.pager.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.selection.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.columnsresize.js"></script>
<script type="text/javascript" src="jqwidgets/jqxlistbox.js"></script>
<script type="text/javascript" src="jqwidgets/jqxdata.export.js"></script> 

<script type="text/javascript" src="jqwidgets/jqxgrid.edit.js"></script>
<script type="text/javascript" src="jqwidgets/jqxtabs.js"></script>
<script type="text/javascript" src="jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="jqwidgets/jqxpanel.js"></script>
<!--    <script type="text/javascript" src="jqwidgets/jqxcore.elements.js"></script>
    <script type="text/javascript" src="jqwidgets/jqxtree.js"></script>-->
<script type="text/javascript" src="jqwidgets/jqxtooltip.js"></script>
<script type="text/javascript" src="jqwidgets/jqxpivot.js"></script> 
<script type="text/javascript" src="jqwidgets/jqxpivotgrid.js"></script>
<script type="text/javascript" src="jqwidgets/jqxpivotdesigner.js"></script>
<script type="text/javascript" src="jqwidgets/jqxwindow.js"></script>
<script type="text/javascript" src="jqwidgets/jqxcheckbox.js"></script>
<script type="text/javascript" src="jqwidgets/jqxdragdrop.js"></script>




    